# Generated by Django 3.2.2 on 2021-10-25 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_rename_category_id_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
