# Generated by Django 3.2.8 on 2021-11-02 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0004_board_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
        migrations.RemoveField(
            model_name='board',
            name='hits',
        ),
        migrations.RemoveField(
            model_name='board',
            name='tag',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
